###########################################################
# Dockerfile that builds a TF2 Gameserver
###########################################################
FROM cm2network/steamcmd:root AS build_stage

LABEL maintainer="walentinlamonos@gmail.com"

ENV STEAMAPPID=232250
ENV STEAMAPP=tf
ENV STEAMAPPDIR="${HOMEDIR}/${STEAMAPP}-dedicated"

COPY "etc/entry.sh" "${HOMEDIR}/entry.sh"
COPY "etc/cfg" "${STEAMAPPDIR}/${STEAMAPP}/cfg/"

RUN set -x \
	# Add i386 architecture
	&& dpkg --add-architecture i386 \
	# Install, update & upgrade packages
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		wget=1.25.0-2 \
		ca-certificates=20250419 \
		lib32z1=1:1.3.dfsg+really1.3.1-1+b1 \
		libncurses6:i386=6.5+20250216-2 \
		libbz2-1.0:i386=1.0.8-6 \
		libtinfo6:i386=6.5+20250216-2 \
		libcurl3t64-gnutls:i386=8.14.1-2+deb13u2 \
	&& mkdir -p "${STEAMAPPDIR}" \
	# Create autoupdate config
	&& { \
		echo '@ShutdownOnFailedCommand 1'; \
		echo '@NoPromptForPassword 1'; \
		echo 'force_install_dir '"${STEAMAPPDIR}"''; \
		echo 'login anonymous'; \
		echo 'app_update '"${STEAMAPPID}"''; \
		echo 'quit'; \
	   } > "${HOMEDIR}/${STEAMAPP}_update.txt" \
	&& chmod +x "${HOMEDIR}/entry.sh" \
	&& chown -R "${USER}:${USER}" "${HOMEDIR}/entry.sh" "${STEAMAPPDIR}" "${HOMEDIR}/${STEAMAPP}_update.txt" \
	# Clean up
	&& rm -rf /var/lib/apt/lists/*

FROM build_stage AS trixie-base

ENV SRCDS_FPSMAX=300 \
        SRCDS_TICKRATE=66 \
        SRCDS_PORT=27015 \
        SRCDS_TV_PORT=27020 \
        SRCDS_NET_PUBLIC_ADDRESS="0" \
        SRCDS_IP="0" \
        SRCDS_MAXPLAYERS=16 \
        SRCDS_STARTMAP="ctf_2fort" \
        SRCDS_REGION=3 \
        SRCDS_HOSTNAME="New \"${STEAMAPP}\" Server" \
        SRCDS_WORKSHOP_START_MAP=0 \
        SRCDS_HOST_WORKSHOP_COLLECTION=0 \
        SRCDS_CFG="server.cfg" \
        SRCDS_MAPCYCLE="mapcycle.txt" \
        SRCDS_SECURED=1 \
        SRCDS_SDR_FAKEIP=0 \
        SRCDS_REPLAY=0 \
        SRCDS_BINARY="srcds_run_64"

RUN --mount=type=secret,id=srcds_token,env=SRCDS_TOKEN \
    --mount=type=secret,id=srcds_rconpw,env=SRCDS_RCONPW \
    --mount=type=secret,id=srcds_pw,env=SRCDS_PW \
    --mount=type=secret,id=srcds_workshop_authkey,env=SRCDS_WORKSHOP_AUTHKEY .

# Switch to user
USER ${USER}

WORKDIR ${HOMEDIR}

CMD ["bash", "entry.sh"]

# Expose ports
EXPOSE 27015/tcp \
	27015/udp \
	27020/udp

FROM trixie-base AS trixie-metamod

ENV METAMOD_VERSION=1.12

FROM trixie-metamod AS trixie-sourcemod

ENV SOURCEMOD_VERSION=1.12
